name: Django CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.5

    - name: Set up Python
      uses: actions/setup-python@v2.5.2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r testproject/requirements.txt

    - name: Run tests
      run: |
        python testproject/manage.py test
